avetiz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	
	#match /help/
	url(r'^help/', include('help.urls')),
	url(r'^api', include('help.urls')),
	url(r'^account/',include('account.urls')),
	url(r'^property/',include('property.urls')),
    url(r'^',include('home.urls')),
    url(r'^request/', views.getFeature, name='ajaxfeature'),
    url(r'^pmi/', include('pmi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

help/urls.py
from django.conf.urls import url
from . import views

app_name='help'

urlpatterns = [
    #match localhost/help/
    url(r'^$', views.help_form, name='helpform'),
	#match localhost/help/request/
	url(r'^request/$', views.complaint, name='complaint'),
	url(r'^/get_help/', views.get_help, name='get_help'),
	url(r'^/(?P<help_id>\d+)$', views.detailhelp, name='detail'),
]

pmi/urls.py
from django.conf.urls import url
#from .views import mortageList
from . import views

app_name='pmi'
urlpatterns = [
url(r'^$', views.mortageList.as_view(), name='pmilist'),
url(r'^ajax_product_list/$',views.ajax_get_product_list, name='ajax_product_list')
]

property/urls.py
from django.conf.urls import url
from . import views

app_name='property'

urlpatterns = [
	url(r'^$', views.listProperty ,name='listing'),
	url(r'searchpage/$', views.searchProperty, name='searchpage' ),
	url(r'detail/(?P<property_id>\d+)/$', views.propertyDetail, name='detail'),
	
	]

help/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Help(models.Model):
	title=models.CharField(max_length=200)
	answer=models.TextField()
	#cat=models.CharField(max_length=200, default='buyer')
	#main=models.BooleanField(default=False)
	
	def __str__(self):
		return self.title



	
		
	
	
	
	

help/forms.py
from django import forms 
from .choices import PROFESSION_CHOICES

class SearchForm(forms.Form):
    help=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control input-lg', 'placeholder':'Search for Help'}))

class TopForm(forms.Form):
	help=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control tops', 'placeholder':'Search for Help'}))

class ComplaintForm(forms.Form):
	profession=forms.ChoiceField(label='Please tell us who you are',widget=forms.Select(attrs={'class':'form-control square'}),choices = PROFESSION_CHOICES)
	email=forms.EmailField(label='Your email address',widget=forms.EmailInput(attrs={'class':'form-control square'}))
	subject=forms.CharField(label='Subject',widget=forms.TextInput(attrs={'class':'form-control square'}))
	description=forms.CharField(label='Description',help_text='Please enter the details of your request. A member of our support staff will respond as soon as possible.',widget=forms.Textarea(attrs={'class':'form-control square','rows':'4'}))
	issue=forms.ChoiceField(label='Issue Type',widget=forms.Select(attrs={'class':'form-control square'}),choices = PROFESSION_CHOICES)
	#attachment=forms.FileField(label='Attachment',widget=forms.FileInput(attrs={'class':'form-control'}))

	

	
	
    

help/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from .models import Help
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .forms import SearchForm
from .models import Help
from .forms import TopForm,ComplaintForm
from django.urls import reverse
from django.core.mail import EmailMessage

import json

def help_form(request):
	if request.method == 'POST':
		form = SearchForm(request.POST)		
		if form.is_valid():
			tit= form.cleaned_data['help']
			try:
				form = TopForm()
				help=Help.objects.get(title=tit)
				return HttpResponseRedirect(reverse('help:detail', kwargs={'help_id':help.id}))
			except ObjectDoesNotExist:
				form = SearchForm()
				return render(request, 'help/helppage.html', {'form':form, 'error':'No results found for "'+tit+'"'})
		else:
			form = SearchForm()
			return render(request, 'help/helppage.html', {'form':form,'error':form.errors})
	else:
		form = SearchForm()
		return render(request, 'help/helppage.html', {'form':form})


def get_help(request):
	if request.is_ajax():
		q = request.GET.get('term', '')
		helps = Help.objects.filter(title__icontains = q )
		results = []
		for help in helps:
			help_json = {}
			help_json = help.title
			results.append(help_json)
		data = json.dumps(results)
	else:
		data = 'fail'
	mimetype = 'application/json'
	return HttpResponse(data, mimetype)

def detailhelp(request, help_id='1'):
	if request.method=='POST':
		form=TopForm(request.POST)
		if form.is_valid():
			tit= form.cleaned_data['help']
			try:
				form=TopForm()
				help=Help.objects.get(title=tit)
				return render(request,'help/detailhelp.html', {'help':help, 'form':form})
			except ObjectDoesNotExist:
				return HttpResponseRedirect(reverse('help:detail', kwargs={'help_id':'1'}))
		else:
			form = TopForm()
			return render(request, 'help/detailhelp.html', {'form':form,'error':form.errors})
	else:
		form=TopForm()
		help=Help.objects.get(id=help_id)
		return render(request, 'help/detailhelp.html', {'form':form, 'help':help, 'message':'Please enter a keyword in the search box'})

def complaint(request):
	if request.method=='POST':
		form=ComplaintForm(request.POST)
		if form.is_valid():
			subject= form.cleaned_data['subject']
			email = EmailMessage(
								subject='Message From Avetiz Help Form. Subject: '+subject,
								body=form.cleaned_data['description'],
								from_email=form.cleaned_data['email'],
								to=['recruitment@avetiz.com'],
								reply_to=[form.cleaned_data['email']]
								)
			email.send(fail_silently=False)	
			return HttpResponseRedirect(reverse('help:helpform',current_app='help'))
		else:
			return render(request, 'help/complaintform.html', {'form':form, 'errors':form.errors})
	else:
		form=ComplaintForm()
		form2=TopForm()
		return render(request, 'help/complaintform.html', {'form':form, 'form2':form2})
	
		
	
			

property/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.db.models import Q
from django.db.models import Avg,Count
from django.core.exceptions import ObjectDoesNotExist
from home.forms import queryForm
from django.core import serializers
from avetiz import settings
import pdb
import math
from datetime import date


def listProperty(request):
	if request.method == 'POST':
		form = SortForm(request.POST)	
		if form.is_valid():
			order= form.cleaned_data['order_by_column']
			limit=form.cleaned_data['limit']
			property=Property.objects.all().order_by(order)
			paginator = Paginator(property, limit) # Show limit property per page
			page = request.GET.get('page')
			try:
				listing= paginator.page(page)
			except PageNotAnInteger:
				listing = paginator.page(1)
			except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
				listing = paginator.page(paginator.num_pages)
		return render(request, 'property/property.html', {'property': listing, 'form':SortForm()})
	
	property=Property.objects.all().order_by('value')
	paginator = Paginator(property, 6) # Show 25 contacts per page
	page = request.GET.get('page')
	try:
		listing= paginator.page(page)
	except PageNotAnInteger:
		listing = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		listing = paginator.page(paginator.num_pages)
	return render(request, 'property/property.html', {'property': listing, 'form':SortForm()})

	
def searchProperty(request):	
	if not request.method=='POST':
		if 'search_parameter' in request.session:
			request.POST=request.session['search_parameter']
			request.method='POST'
		else:
			form=queryForm()
			return render(request,'home/index.html', {'searchform':form})

	if request.method=='POST':
		request.session['search_parameter']=request.POST
		#pdb.set_trace()
		if 'topform' in request.POST :
			topform=topForm(request.POST)
			if topform.is_valid():
				city=topform.cleaned_data['city']
				state=topform.cleaned_data['state']
				country=topform.cleaned_data['country']
				query=topform.cleaned_data['search']
				types=topform.cleaned_data['propertytype']
				bedno=topform.cleaned_data['bedno']
				bathno=topform.cleaned_data['bathno']
				if city:
					result=Property.objects.filter(city__icontains=city)
					result=topFormFilter(types,bedno,bathno,result)	
					if not result.exists():
						result=Property.objects.filter(state__icontains=state)
						result=topFormFilter(types,bedno,bathno,result)

					if not result.exists():
						result=Property.objects.filter(feature=True)						
						listing=getlisting(result,3,request)
						return render(request,'property/search.html',{'result':listing,'topform':topForm(),'filterform':filterForm()})	
				
				if state and not city:
					result=Property.objects.filter(state__icontains=state)
					result=topFormFilter(types,bedno,bathno,result)			
					if not result.exists():							
						result=Property.objects.filter(feature=True)						
						listing=getlisting(result,3,request)
						return render(request,'property/search.html',{'result':listing,'topform':topForm(),'filterform':filterForm()})
				
				if not state and not city:
					#pdb.set_trace()
					context=get_no_result_context(query=query,request=request,types=types,bedno=bedno,bathno=bathno)	
					#pdb.set_trace()	
					return render(request, 'property/search.html',context)
				context=getContext(city,country,state,result,request,query,types,bedno,bathno,'home')
				request.session['count']=result.count()
				request.session['query']=query
				return render(request,'property/search.html',context)

		elif 'minprice' in request.POST or 'maxprice' in request.POST:
			form=filterForm(request.POST)	
			
			return render(request,'property/search.html',context)

		elif 'hiddenquery' in request.POST and request.POST.get('hiddentypeoforder') == 'newest':
			#pdb.set_trace()
			city=request.POST.get('hiddencity')
			state=request.POST.get('hiddenstate')
			country=request.POST.get('hiddencountry')
			query=request.POST.get('hiddenquery')
			bedno=request.POST.get('hiddenbedno')
			bathno=request.POST.get('hiddenbathno')
			types=request.POST.get('hiddenpropertytype')
			try:
				resultcount=int(request.POST.get('count'))
			except:
				resultcount=0
			if city:
				result=Property.objects.filter(city__icontains=city).order_by('-uploadDate')
				if not result.exists()  or result.count != resultcount :
					result=Property.objects.filter(state__icontains=state).order_by('-uploadDate')
					if not result.exists() or result.count() != resultcount:
						result=Property.objects.filter(state__icontains=state).order_by('-uploadDate')
						if not result.exists()  or result.count() != resultcount:
							context=get_no_result_context(query=query,request=request, highlight='newest')		
							return render(request, 'property/search.html',context)
							#result=Property.objects.filter(Q(state__icontains=query)|Q(city__icontains=query)|Q(Country__icontains=query)|Q(street__icontains=query)).order_by('-uploadDate')
							if not result.exists():
								result=Property.objects.filter(feature=True)
								listing=getlisting(result,3,request)
								return render(request,'property/search.html',{'result':listing,'topform':topForm()})
					
			if state and not city:
				result=Property.objects.filter(state__icontains=state).order_by('-uploadDate')
				if not result.exists()  or result.count() != resultcount:
					result=Property.objects.filter(Q(state__icontains=query)|Q(city__icontains=query)|Q(Country__icontains=query)|Q(street__icontains=query)).order_by('-uploadDate')
					if not result.exists():
						result=Property.objects.filter(feature=True)
						listing=getlisting(result,3,request)
						return render(request,'property/search.html',{'result':listing,'topform':topForm()})
			if not state and not city:
				#pdb.set_trace()
				context=get_no_result_context(query=query,request=request, highlight='newest')		
				return render(request, 'property/search.html',context)
			#pdb.set_trace()
			context=getContext(city,country,state,result,request,query,types,bedno,bathno,'newest')
			return render(request,'property/search.html',context)

		elif 'hiddenquery' in request.POST and request.POST.get('hiddentypeoforder')=='homes':
			#pdb.set_trace()
			city=request.POST.get('hiddencity')
			state=request.POST.get('hiddenstate')
			country=request.POST.get('hiddencountry')
			query=request.POST.get('hiddenquery')
			bedno=request.POST.get('hiddenbedno')
			bathno=request.POST.get('hiddenbathno')
			types=request.POST.get('hiddenpropertytype')
			resultcount=int(request.POST.get('count'))
			#pdb.set_trace()
			if city:
				result=Property.objects.filter(city__icontains=city)
				if not result.exists()  or result.count() != resultcount :
					result=Property.objects.filter(state__icontains=state)
					if not result.exists() or result.count() != resultcount:
						result=Property.objects.filter(state__icontains=state)
						if not result.exists()  or result.count() != resultcount:
							result=Property.objects.filter(Q(state__icontains=query)|Q(city__icontains=query)|Q(Country__icontains=query)|Q(street__icontains=query))
							if not result.exists():
								result=Property.objects.filter(feature=True)
								listing=getlisting(result,3,request)
								return render(request,'property/search.html',{'result':listing,'topform':topForm()})
					
			if state and not city:
				result=Property.objects.filter(state__icontains=state)
				if not result.exists():
					result=Property.objects.filter(feature=True)
					listing=getlisting(result,3,request)
					return render(request,'property/search.html',{'result':listing,'topform':topForm()})
			if not state and not city:
				#pdb.set_trace()
				context=get_no_result_context(query=query,request=request)		
				return render(request, 'property/search.html',context)
			context=getContext(city,country,state,result,request,query,types,bedno,bathno,'home')
			return render(request,'property/search.html',context)

		elif 'hiddenquery' in request.POST and request.POST.get('hiddentypeoforder')=='cheap':
			city=request.POST.get('hiddencity')
			state=request.POST.get('hiddenstate')
			country=request.POST.get('hiddencountry')
			query=request.POST.get('hiddenquery')
			bedno=request.POST.get('hiddenbedno')
			bathno=request.POST.get('hiddenbathno')
			types=request.POST.get('hiddenpropertytype')
			resultcount=int(request.POST.get('count'))
			if city:
				result=Property.objects.filter(city__icontains=city).order_by('value')
				if not result.exists()  or result.count() != resultcount :
					result=Property.objects.filter(state__icontains=state).order_by('value')
					if not result.exists() or result.count() != resultcount:
						result=Property.objects.filter(state__icontains=state).order_by('value')
						if not result.exists()  or result.count() != resultcount:
							result=Property.objects.filter(Q(state__icontains=query)|Q(city__icontains=query)|Q(Country__icontains=query)|Q(street__icontains=query)).order_by('value')
							if not result.exists():
								result=Property.objects.filter(feature=True)
								listing=getlisting(result,3,request)
								return render(request,'property/search.html',{'result':listing,'topform':topform})
					
			if state and not city:
				result=Property.objects.filter(state__icontains=state).order_by('value')
				if not result.exists():
					result=Property.objects.filter(feature=True)
					listing=getlisting(result,3,request)
					return render(request,'property/search.html',{'result':listing,'topform':topform})
			if not state and not city:

help/templates/help/base.html
{% load static %}
<title>AvetiZ</title>
  <meta charset = "utf-8">
  <meta http-equiv = "X-UA-Compatible" content = "IE=edge">
  <meta name = "viewport" content = "width = device width, initial-scale = 1">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'property/css/footer.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'help/css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <link rel="shortcut icon" sizes="76x76" type="image/x-icon" href="{% static 'help/img/logo.png' %}" />
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyC8TvKHQ-rUklU5OsD6Oq73pMG1fJO9iR8" ></script>
  <link rel="stylesheet" type="text/css" href="{% static 'property/property.css'%}">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
  
  </head>
<body onload="geoFindMe()">
<!-- Navigation Bar Section -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img class ="img-responsive" src="{% static 'help/img/logo.png' %}"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Sign Up</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="#" data-toggle="modal" data-target="#search" ><i class="fa fa-map-marker fa-2x locator" aria-hidden="true"></i></a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!--- Modal View Section-->	
	<div id="search" class="modal fade" role="dialog">
					<div class="modal-dialog">

    <!-- Modal content-->
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<h4 class="modal-title" id="city">.</h4>
							</div>
							<div class="modal-body">
							
								<p>We Use Location to customize the information you see.</p>
								
								<input type="text" id="pac-input" class="form-control" placeholder="Change your location"  />
								<!--div class="pac-container"></div-->
								
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							</div>
						</div>

					</div>
	</div>
	<!--- Modal View Section-->	
	<div id="search" class="modal fade" role="dialog">
					<div class="modal-dialog">

    <!-- Modal content-->
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<h4 class="modal-title" id="city">.</h4>
							</div>
							<div class="modal-body">
							
								<p>We Use Location to customize the information you see.</p>
								
								<input type="text" id="pac-input" class="form-control" placeholder="Change your location"  />
								<!--div class="pac-container"></div-->
								
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							</div>
						</div>

					</div>
	</div>
	
	<!--End of Model Section-->
	 {% block content %}
     {% endblock %}


<!--footer section -->	
<div class="divider-5"></div>
<hr>

<div class="container"> 
<div class="footer">
  
    <div class="row">
      
      <div class="col-sm-4 more-space"><!--  1st column begins-->
      
        <!--h4 class="column-header text-justify head"> AvetiZ </h2-->
        
        
        <div class="more-space">
      
				<div class="col-md-8 mavelous ">
					
					
					<div class="form-group">
						
						<div id="google_translate_element"></div><script type="text/javascript">
								function googleTranslateElementInit() {
										new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'ar,de,en,fr,zh-CN', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
										}
									</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
					</div>	
			
				</div>
             
        <div class="col-sm-8 mavelous currency">
          
          <div class="form-group">
          
            <select name="currency_code" class="form-control tolu">
                <option value="NGN">NGN</option>
                <option value="AUD">USD</option>
                <option value="BRL">EUR </option>
                <option value="CAD">CAD</option>
                <option value="CZK">GBP</option>
                
            </select>
          
          </div>
    
        </div>

        
        <div class="divider-10"></div>
        
        <div class="col-sm-12 ">
        
          <ul class="list-group text-justify  borderless list-inline">
              <li class="list-group-item">Terms</li>
              <li class="list-group-item">Privacy</li>
              <li class="list-group-item">Site Map</li>
              <li class="list-group-item"><span><i class="fa fa-facebook-official fa-1x"></i></span></li>
              <li class="list-group-item"><i class="fa fa-linkedin fa-1x"></i></li>
              <li class="list-group-item"><i class="fa fa-instagram fa-1x" aria-hidden="true"></i></li>
          </ul>
        
        </div>
        
  
        
        
        
        </div><!--more space div add margin top -->
        
      
      </div><!-- end of 1st column-->
      
      
      <div class="col-sm-4 more-space"><!--  2nd column begins-->
      
         
          
          <div class="more-space">
          
           <h4 class="column-header text-justify head"> Sign Up </h4>
          
          <ul class="list-group text-justify mavelous borderless">
            <li class="list-group-item">About</li>
            <li class="list-group-item">Help</li>
            <li class="list-group-item">Investors</li>
            <li class="list-group-item">Partners</li>
            <li class="list-group-item">Cities</li>
            <li class="list-group-item">Policies</li>
            <li class="list-group-item">Countries</li>
            <!--li class="list-group-item">About Us</li-->
            
            
            
          </ul>
          
          </div>
      
      
      </div><!-- end of 2nd column-->
    
    
      
      <div class="col-sm-3 more-space"><!--  3nd column begins-->
      
          
          
          
          
          <div class="more-space">
			<h4 class="column-header text-justify head "> Help </h4>
          <ul class="list-group text-justify mavelous borderless">
            <li class="list-group-item">Safety</li>
            <li class="list-group-item">Media</li>
            <li class="list-group-item">How it Works</li>
            <li class="list-group-item">Intelligent Investments</li>
            <li class="list-group-item">Research</li>
            <!--li class="list-group-item">Local Jobs</li-->
          </ul>
          
          </div>
      
    
      
      </div><!-- end of 3nd column-->
      
      <div class="col-sm-1 ">
		<!--div class="divider-icon"></div-->
        <div class="col-sm-push-3" >
		
                                 
        <div id="search" class="modal fade" role="dialog">
          <div class="modal-dialog">

    <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Lagos</h4>
              </div>
              <div class="modal-body">
              
                <p>We Use Location to customize the information you see.</p>
                
                <input type="text" id="pac-input" class="form-control" placeholder="Change your location"  />
                <!--div class="pac-container"></div-->
                
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
        </div>
        
        </div>
      
      </div>
	</div><!--row -->
	</div> 
    
  </div><!--container --> 
  <hr>
      
   <div class="container">
     <div class="row">
      <div class="col-sm-6">
      <span><p class="head">AvetiZ is a service mark of AvetiZ Corp &copy; 2017. All Rights Reserved.</p></span>
      </div>
      
        <div class="col-sm-4 border-header"><!-- android ios download section -->
           <ul class="list-group text-center borderless list-inline">
            <li class="list-group-item"><img src="{% static 'help/img/google2.png' %}" class="img-responsive "></li>
            <li class="list-group-item"><img src="{% static 'help/img/ios2.png' %}" class="img-responsive "></li> 
          </ul>  
       </div>
       </div>
     </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>


<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'help/js/main.js' %}"></script>
<script>
			
			google.maps.event.addDomListener(window, 'load', initialize);
			function initialize() {
				var options = {
								types: ['(cities)'],
								radius: '2000',
								location:'6.5243793,3.379205700000057',
								componentRestrictions: {country: "us,ng"}
								
								};
				var input = document.getElementById('pac-input',options);
				var autocomplete = new google.maps.places.Autocomplete(input);
				autocomplete.addListener('place_changed', function () {
				var place = autocomplete.getPlace();
			// place variable will have all the information you are looking for.
				console.log(place.geometry['location'].lat());
				console.log(place.geometry['location'].lng());
				longitude=place.geometry['location'].lng();
				latitude=place.geometry['location'].lat();
				displayLocation(latitude,longitude);
				
				
				});
				}
				
				
				
				function geoFindMe() {
				
					if(navigator.geolocation) {
						navigator.geolocation.getCurrentPosition(success, error, geoOptions);
						} else {
					console.log("Geolocation services are not supported by your web browser.");
				}
				$('#developers-section').hide();
				$('#professionals-section').hide();
				$('#start-section').hide();
				$('#buyer-section').show();
			}

			function success(position) {
				var latitude = position.coords.latitude;
				var longitude = position.coords.longitude;
				var altitude = position.coords.altitude;
				var accuracy = position.coords.accuracy;
				console.log("lat: " + latitude + " long: " + longitude);
				displayLocation(latitude,longitude);
				}

			function error(error) {
				console.log("Unable to retrieve your location due to " + error.code + ": " + error.message);
			}

			var geoOptions = {
			enableHighAccuracy: true,
			maximumAge: 30000,
			timeout: 27000
			};
			
		
				
function displayLocation(latitude,longitude){
    var geocoder;
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(latitude, longitude);

    geocoder.geocode(
        {'latLng': latlng}, 
        function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[0]) {
                    var add= results[0].formatted_address ;
                    var  value=add.split(",");

                    count=value.length;
                    country=value[count-1];
                    state=value[count-2];
                    city=value[count-3];
					var x=document.getElementById("city");
					
					
					x.innerHTML = state;
                    console.log ("city name is: " + city);
                }
                else  {
                    console.log ("address not found");
                }
            }
            else {
                console.log( "Geocoder failed due to: " + status);
            }
        }
    );
}		 
		 
</script>

<script>
		 $(function() {
    $("#id_help").autocomplete({
      source: "/api/get_help/",
      select: function (event, ui) { //item selected
        AutoCompleteSelectHandler(event, ui)
      },
      minLength: 1,
		});
		});

  function AutoCompleteSelectHandler(event, ui)
  {
    var selectedObj = ui.item;
  }

	
	</script>



</body>
</html>